### ISSUE TITLE
No support for arm64

### ISSUE THREAD

**Issue by LanYunDev** [viddotech/videoalchemy#12]
### What happened?

➜  ./videoalchemy
zsh: exec format error: ./videoalchemy
➜  file ./videoalchemy
./videoalchemy: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=PlVDdAcT5MTs2n3-EztI/1myd8kU7lQ5CoEeVqSLJ/5JsYtQUUDikWFcFPQORB/iFxiWiX84cfiHjs8Ypj_, with debug_info, not stripped
➜  uname -a
Darwin macbook-pro 24.2.0 Darwin Kernel Version 24.2.0: Fri Dec  6 19:01:59 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T6000 arm64

### What did you expect to happen?

Normal operation

### How can we reproduce it (as minimally and precisely as possible)?

run on arm64

### VideoAlchemy version

1.0-RC1

### OS

MacOS

**Comment by hsngerami** [comment]
@LanYunDev added build of arm64. please download from https://github.com/viddotech/videoalchemy/releases/tag/1.0.0-RC1
