### ISSUE TITLE
zsh completions do not work as expected

### ISSUE THREAD

**Issue by ethereal-engineer** [viddotech/videoalchemy#6]
### What happened?

```
❯ source <(VideoAlchemy completion zsh)
zsh: command not found: VideoAlchemy

❯ source <(videoalchemy completion zsh)
/proc/self/fd/11:1: command not found: Version:
```

Also tried to modify the output completion for inclusion in my dotfiles. Note that following instructions from the README.md downloads the binary as `videoalchemy` (all lowercase).

### What did you expect to happen?

Completions!

### How can we reproduce it (as minimally and precisely as possible)?

1. run zsh
2. follow install instructions

### Anything else we need to know?

Don't think so.

### VideoAlchemy version

0.0.1-alpha

### OS

Linux

**Comment by ethereal-engineer** [comment]
If you output the version info into stderr, you can still have it output the version while doing this if needed

**Comment by hsngerami** [comment]
@ethereal-engineer please check new installation command.
